### ISSUE TITLE
MYSQL environment and ModuleNotFoundError error

### ISSUE THREAD

**Issue by mertcangokgoz** [roxy-wi/roxy-wi#393]
~~I'm using roxy with docker and I got the following error when upgrading to v8. The interface works but I can't login to the system with my username and password because the database is also reset during the update, so why is this happening?~~

I just pulled the new image from the repo, I use docker compose. 

ERROR

```
2024-09-03 13:29:16,496 INFO exited: roxy-wi-portscanner (exit status 1; not expected)
2024-09-03 13:29:19,501 INFO spawned: 'roxy-wi-checker' with pid 473
2024-09-03 13:29:19,503 INFO spawned: 'roxy-wi-keep_alive' with pid 474
2024-09-03 13:29:19,504 INFO spawned: 'roxy-wi-metrics' with pid 475
2024-09-03 13:29:19,506 INFO spawned: 'roxy-wi-portscanner' with pid 476
2024-09-03 13:29:19,507 INFO spawned: 'roxy-wi-prometheus-exporter' with pid 477
2024-09-03 13:29:19,508 INFO spawnerr: command at '/var/www/haproxy-wi/app/tools/smon.py' is not executable
2024-09-03 13:29:19,508 INFO gave up: roxy-wi-smon entered FATAL state, too many start retries too quickly
2024-09-03 13:29:19,509 INFO spawned: 'roxy-wi-socket' with pid 478
supervisor: couldn't exec /var/www/haproxy-wi/app/tools/checker_master.py: ENOEXEC
supervisor: child process was not spawned
2024-09-03 13:29:19,509 INFO exited: roxy-wi-checker (exit status 127; not expected)
supervisor: couldn't exec /var/www/haproxy-wi/app/tools/keep_alive.py: ENOEXEC
supervisor: child process was not spawned
2024-09-03 13:29:19,509 INFO exited: roxy-wi-keep_alive (exit status 127; not expected)
supervisor: couldn't exec /var/www/haproxy-wi/app/tools/metrics_master.py: ENOEXEC
supervisor: child process was not spawned
2024-09-03 13:29:19,509 INFO exited: roxy-wi-metrics (exit status 127; not expected)
supervisor: couldn't exec /var/www/haproxy-wi/app/tools/prometheus_exporter.py: ENOEXEC
2024-09-03 13:29:19,511 INFO gave up: roxy-wi-checker entered FATAL state, too many start retries too quickly
2024-09-03 13:29:19,511 INFO gave up: roxy-wi-keep_alive entered FATAL state, too many start retries too quickly
2024-09-03 13:29:19,511 INFO gave up: roxy-wi-metrics entered FATAL state, too many start retries too quickly
supervisor: child process was not spawned
supervisor: couldn't exec /var/www/haproxy-wi/app/tools/sockets.py: ENOEXEC
supervisor: child process was not spawned
2024-09-03 13:29:19,514 INFO exited: roxy-wi-prometheus-exporter (exit status 127; not expected)
2024-09-03 13:29:19,514 INFO gave up: roxy-wi-prometheus-exporter entered FATAL state, too many start retries too quickly
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/tools/port_scanner.py", line 10, in <module>
    from retry import retry
ModuleNotFoundError: No module named 'retry'
2024-09-03 13:29:19,550 INFO exited: roxy-wi-socket (exit status 127; not expected)
2024-09-03 13:29:19,555 INFO gave up: roxy-wi-socket entered FATAL state, too many start retries too quickly
2024-09-03 13:29:19,555 INFO exited: roxy-wi-portscanner (exit status 1; not expected)
2024-09-03 13:29:20,556 INFO gave up: roxy-wi-portscanner entered FATAL state, too many start retries too quickly
```

**Comment by Aidaho12** [comment]
Try to update DB with file https://roxy-wi.org/update-guide#8

**Comment by mertcangokgoz** [comment]
@Aidaho12 Thank you, this information was not in the documentation on the docker side. 

It would be good to improve the docker documentation.

**Comment by mertcangokgoz** [comment]
Yes, my database problem has disappeared, `ModuleNotFoundError: No module named ‘retry’` continues. What solution do you suggest to this?

**Comment by Aidaho12** [comment]
Install inside Roxy-WI retry:
```
pip3.11 install retry
```

**Comment by mertcangokgoz** [comment]
> Install inside Roxy-WI retry:
> 
> ```
> pip3.11 install retry
> ```

but a temporary solution :)

**Comment by Aidaho12** [comment]
Next image will have it

**Comment by mertcangokgoz** [comment]
In the new installation, there is a situation like this, the database does not migrate.

```
[root@haproxy-gui haproxy-wi]# python3.11 app/create_db.py 
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/create_db.py", line 3, in <module>
    from app.modules.db.db_model import (
ModuleNotFoundError: No module named 'app'
```

**Comment by mertcangokgoz** [comment]
After migration, new tables are not created in mariadb, is this normal?

<img width="478" alt="image" src="https://github.com/user-attachments/assets/acc7d693-571f-4a0b-b68c-1d8c3c3b92b8">

The docker compose I use is as follows, but I don't understand that it doesn't use mariadb.

<img width="271" alt="image" src="https://github.com/user-attachments/assets/9d37d870-8689-4fc1-bb8d-5d514efd5130">


docker-compose.yml

```
services:
  haproxy-gui:
    image: registry.roxy-wi.org/roxy-wi:latest
    container_name: haproxy-gui
    hostname: haproxy-gui
    restart: always
    depends_on:
      - db
    ports:
      - "443:443"
      - "8765:8765"
    volumes:
      - roxy-wi-data:/var/roxy-wi/lib
      - roxy-wi-conf:/etc/roxy-wi
      - roxy-wi-repo:/etc/yum.repos.d/
      - roxy-wi-python:/usr/local/lib/python3.11/ # pip3.11 install retry fixes
    environment:
      - MYSQL_ENABLE=1
      - MYSQL_DB=roxy-wi
      - MYSQL_USER=REDACTED
      - MYSQL_PASSWORD=REDACTED
      - MYSQL_HOST=db
    networks:
      - roxy-wi-net

  db:
    image: mariadb:latest
    container_name: haproxy-gui-db
    hostname: haproxy-gui-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - roxy-wi-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_DATABASE=roxy-wi
      - MYSQL_USER=REDACTED
      - MYSQL_PASSWORD=REDACTED
    networks:
      - roxy-wi-net


volumes:
  roxy-wi-data:
  roxy-wi-conf:
  roxy-wi-repo:
  roxy-wi-database:
  roxy-wi-python:

networks:
  roxy-wi-net: {}
```

**Comment by Aidaho12** [comment]
You shouldn't run create_db separately now. Check roxy-wi.cfg if it's ok, just restart container

**Comment by mertcangokgoz** [comment]
docker env ok
internal env ok
roxy-wi.cfg env failed****

Although I edited the envs, it didn't change the cfg in any way :S I don't know why.
```

[mysql]
# By default Sqlite DB is used
enable = 0
mysql_user = roxy-wi
mysql_password = roxy-wi
mysql_db = roxywi
mysql_host = 127.0.0.0.1
mysql_port = 3306
```

**Comment by Aidaho12** [comment]
It worked before?

**Comment by mertcangokgoz** [comment]
> It worked before?

I honestly didn't have a problem before. In docker-compose - `./roxy-wi.cfg:/etc/roxy-wi/roxy-wi.cfg`, although I sent it from local, I could not run it.

**Comment by Aidaho12** [comment]
Looks like a bug

**Comment by Aidaho12** [comment]
But you can edit config manually config and run create db

**Comment by mertcangokgoz** [comment]
> But you can edit config manually config and run create db

Yes, when I edited it manually, on my 2nd reboot, the migration took place without any problems and mysql was active.
