### ISSUE TITLE
Internal Server Error - import app.modules.db.sql as sql ModuleNotFoundError: No module named 'app' - roxy-wi-socket

### ISSUE THREAD

**Issue by jcervantes-sipecom** [roxy-wi/roxy-wi#406]
Hi,

I'm getting:

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.58 (Ubuntu) Server at IP Port 10443
```

The Socket Service state get failure:
```

**systemctl status roxy-wi-socket**
● roxy-wi-socket.service - Roxy-WI socket
     Loaded: loaded (/etc/systemd/system/roxy-wi-socket.service; disabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-12-11 16:15:06 -05; 805ms ago
    Process: 1813 ExecStart=/usr/bin/python3 /var/www/haproxy-wi/app/tools/sockets.py (code=exited, status=1/FAILURE)
   Main PID: 1813 (code=exited, status=1/FAILURE)
```

If I do: 

>  pip3 install -r /var/www/haproxy-wi/requirements.txt

I got:
```

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

If I do: 

> pip3 install -r /var/www/haproxy-wi/requirements.txt --break-system-packages

I got:

```
pip3 install -r /var/www/haproxy-wi/requirements.txt --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 1)) (7.1.0)
Requirement already satisfied: paramiko-ng>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 2)) (2.8.10)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 3)) (2024.2)
Requirement already satisfied: tzlocal==2.0.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 4)) (2.0.0)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 5)) (2.32.3)
Requirement already satisfied: pyTelegramBotAPI>=3.6.3 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 6)) (4.24.0)
Requirement already satisfied: networkx>=2.6 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 7)) (3.4.2)
Requirement already satisfied: matplotlib>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 8)) (3.9.3)
Requirement already satisfied: future>=0.13.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: jinja2>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 10)) (3.1.4)
Requirement already satisfied: slack-sdk>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 11)) (3.33.5)
Requirement already satisfied: peewee>=3.14.10 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 12)) (3.17.8)
Requirement already satisfied: PyMySQL>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 13)) (1.1.1)
Requirement already satisfied: distro>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 14)) (1.9.0)
Requirement already satisfied: psutil>=5.9.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 15)) (6.1.0)
Requirement already satisfied: pdpyras>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 16)) (5.3.0)
Requirement already satisfied: pika>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 17)) (1.3.2)
Requirement already satisfied: Werkzeug==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 18)) (3.0.3)
Requirement already satisfied: Flask==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 19)) (3.0.3)
Requirement already satisfied: Flask-APScheduler==1.13.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 20)) (1.13.1)
Requirement already satisfied: Flask-Caching==2.3.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 21)) (2.3.0)
Requirement already satisfied: Flask-JWT-Extended==4.6.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 22)) (4.6.0)
Requirement already satisfied: Flask-Pydantic==0.12.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 23)) (0.12.0)
Requirement already satisfied: flask-swagger==0.2.14 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 25)) (0.2.14)
Requirement already satisfied: ansible-core==2.16.3 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 26)) (2.16.3)
Requirement already satisfied: ansible-runner==2.3.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 27)) (2.3.1)
Requirement already satisfied: python-whois>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 28)) (0.9.5)
Requirement already satisfied: netaddr>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 29)) (1.3.0)
Requirement already satisfied: retry>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 30)) (0.9.2)
Requirement already satisfied: aio-pika>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 31)) (9.5.3)
Requirement already satisfied: websockets==13.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 33)) (13.1)
Requirement already satisfied: python3-nmap<=1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 34)) (1.5.1)
Requirement already satisfied: pydantic[email] in /usr/local/lib/python3.12/dist-packages (from -r /var/www/haproxy-wi/requirements.txt (line 24)) (2.10.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.3->-r /var/www/haproxy-wi/requirements.txt (line 5)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.3->-r /var/www/haproxy-wi/requirements.txt (line 5)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.3->-r /var/www/haproxy-wi/requirements.txt (line 5)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.3->-r /var/www/haproxy-wi/requirements.txt (line 5)) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Werkzeug==3.0.3->-r /var/www/haproxy-wi/requirements.txt (line 18)) (3.0.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask==3.0.3->-r /var/www/haproxy-wi/requirements.txt (line 19)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask==3.0.3->-r /var/www/haproxy-wi/requirements.txt (line 19)) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.12/dist-packages (from Flask==3.0.3->-r /var/www/haproxy-wi/requirements.txt (line 19)) (1.9.0)
Requirement already satisfied: apscheduler<4.0.0,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask-APScheduler==1.13.1->-r /var/www/haproxy-wi/requirements.txt (line 20)) (3.10.4)
Requirement already satisfied: python-dateutil>=2.4.2 in /usr/local/lib/python3.12/dist-packages (from Flask-APScheduler==1.13.1->-r /var/www/haproxy-wi/requirements.txt (line 20)) (2.9.0.post0)
Requirement already satisfied: cachelib<0.10.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask-Caching==2.3.0->-r /var/www/haproxy-wi/requirements.txt (line 21)) (0.9.0)
Requirement already satisfied: PyJWT<3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from Flask-JWT-Extended==4.6.0->-r /var/www/haproxy-wi/requirements.txt (line 22)) (2.10.1)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from flask-swagger==0.2.14->-r /var/www/haproxy-wi/requirements.txt (line 25)) (6.0.2)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from ansible-core==2.16.3->-r /var/www/haproxy-wi/requirements.txt (line 26)) (44.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from ansible-core==2.16.3->-r /var/www/haproxy-wi/requirements.txt (line 26)) (24.2)
Requirement already satisfied: resolvelib<1.1.0,>=0.5.3 in /usr/local/lib/python3.12/dist-packages (from ansible-core==2.16.3->-r /var/www/haproxy-wi/requirements.txt (line 26)) (1.0.1)
Requirement already satisfied: pexpect>=4.5 in /usr/local/lib/python3.12/dist-packages (from ansible-runner==2.3.1->-r /var/www/haproxy-wi/requirements.txt (line 27)) (4.9.0)
Requirement already satisfied: python-daemon in /usr/local/lib/python3.12/dist-packages (from ansible-runner==2.3.1->-r /var/www/haproxy-wi/requirements.txt (line 27)) (3.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ansible-runner==2.3.1->-r /var/www/haproxy-wi/requirements.txt (line 27)) (1.17.0)
Requirement already satisfied: bcrypt>=3 in /usr/local/lib/python3.12/dist-packages (from paramiko-ng>=2.5.0->-r /var/www/haproxy-wi/requirements.txt (line 2)) (4.2.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (4.55.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (1.4.7)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (2.2.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.1.2->-r /var/www/haproxy-wi/requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic[email]->-r /var/www/haproxy-wi/requirements.txt (line 24)) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /usr/local/lib/python3.12/dist-packages (from pydantic[email]->-r /var/www/haproxy-wi/requirements.txt (line 24)) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic[email]->-r /var/www/haproxy-wi/requirements.txt (line 24)) (4.12.2)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pydantic[email]->-r /var/www/haproxy-wi/requirements.txt (line 24)) (2.2.0)
Requirement already satisfied: decorator>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from retry>=0.9.2->-r /var/www/haproxy-wi/requirements.txt (line 30)) (5.1.1)
Requirement already satisfied: py<2.0.0,>=1.4.26 in /usr/local/lib/python3.12/dist-packages (from retry>=0.9.2->-r /var/www/haproxy-wi/requirements.txt (line 30)) (1.11.0)
Requirement already satisfied: aiormq<6.9,>=6.8 in /usr/local/lib/python3.12/dist-packages (from aio-pika>=7.1.0->-r /var/www/haproxy-wi/requirements.txt (line 31)) (6.8.1)
Requirement already satisfied: exceptiongroup<2,>=1 in /usr/local/lib/python3.12/dist-packages (from aio-pika>=7.1.0->-r /var/www/haproxy-wi/requirements.txt (line 31)) (1.2.2)
Requirement already satisfied: yarl in /usr/local/lib/python3.12/dist-packages (from aio-pika>=7.1.0->-r /var/www/haproxy-wi/requirements.txt (line 31)) (1.18.3)
Requirement already satisfied: simplejson in /usr/local/lib/python3.12/dist-packages (from python3-nmap<=1.5.1->-r /var/www/haproxy-wi/requirements.txt (line 34)) (3.19.3)
Requirement already satisfied: pamqp==3.3.0 in /usr/local/lib/python3.12/dist-packages (from aiormq<6.9,>=6.8->aio-pika>=7.1.0->-r /var/www/haproxy-wi/requirements.txt (line 31)) (3.3.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->ansible-core==2.16.3->-r /var/www/haproxy-wi/requirements.txt (line 26)) (1.17.1)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->pydantic[email]->-r /var/www/haproxy-wi/requirements.txt (line 24)) (2.7.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>=4.5->ansible-runner==2.3.1->-r /var/www/haproxy-wi/requirements.txt (line 27)) (0.7.0)
Requirement already satisfied: lockfile>=0.10 in /usr/local/lib/python3.12/dist-packages (from python-daemon->ansible-runner==2.3.1->-r /var/www/haproxy-wi/requirements.txt (line 27)) (0.12.2)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl->aio-pika>=7.1.0->-r /var/www/haproxy-wi/requirements.txt (line 31)) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from yarl->aio-pika>=7.1.0->-r /var/www/haproxy-wi/requirements.txt (line 31)) (0.2.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->ansible-core==2.16.3->-r /var/www/haproxy-wi/requirements.txt (line 26)) (2.22)
```

My apache2 virtual host justo modify the listen port:

```
Listen 10443
<VirtualHost *:10443>
    AddDefaultCharset UTF-8
    SetEnv PYTHONIOENCODING utf8

    SSLEngine on
    SSLCertificateFile /var/www/haproxy-wi/app/certs/haproxy-wi.crt
    SSLCertificateKeyFile /var/www/haproxy-wi/app/certs/haproxy-wi.key

    ServerName roxy-wi.example.com
    ErrorLog /var/log/apache2/roxy-wi.error.log
    CustomLog /var/log/apache2/roxy-wi.access.log combined
    TimeOut 600
    LimitRequestLine 16380

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)           ws://localhost:8765/ [P,L]
    ProxyPassReverse / http://localhost:8765/

    DocumentRoot /var/www/haproxy-wi
```

If I manually run: 

> /usr/bin/python3 /var/www/haproxy-wi/app/tools/sockets.py

I got:

```
/usr/bin/python3 /var/www/haproxy-wi/app/tools/sockets.py
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/tools/sockets.py", line 16, in <module>
    import app.modules.db.sql as sql
ModuleNotFoundError: No module named 'app'
```

**Comment by Aidaho12** [comment]
Hi, it's not clear for me. Does not work Roxy-WI or socket tool?


To run correctly socket tool manually you should start it from /var/www/haproxy-wi/app

**Comment by jcervantes-sipecom** [comment]
> Hi, it's not clear for me. Does not work Roxy-WI or socket tool?
> 
> To run correctly socket tool manually you should start it from /var/www/haproxy-wi/app

Hi @Aidaho12, none of both, if the socket is not up, the roxy-wi is not up neither.

I tried what you suggested, but not work neither:

**As normal user:**

```
/var/www/haproxy-wi/app$ python3 tools/sockets.py
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/tools/sockets.py", line 16, in <module>
    import app.modules.db.sql as sql
  File "/var/www/haproxy-wi/app/__init__.py", line 9, in <module>
    app.config.from_object('app.config.Configuration')
  File "/usr/local/lib/python3.12/dist-packages/flask/config.py", line 254, in from_object
    obj = import_string(obj)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/werkzeug/utils.py", line 596, in import_string
    __import__(import_name)
  File "/var/www/haproxy-wi/app/config.py", line 4, in <module>
    class Configuration(object):
  File "/var/www/haproxy-wi/app/config.py", line 11, in Configuration
    JWT_PRIVATE_KEY = open('/var/lib/roxy-wi/keys/roxy-wi-key').read()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/lib/roxy-wi/keys/roxy-wi-key'
```

**As sudo user:**

```
/var/www/haproxy-wi/app$ sudo python3 tools/sockets.py
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/tools/sockets.py", line 16, in <module>
    import app.modules.db.sql as sql
  File "/var/www/haproxy-wi/app/__init__.py", line 16, in <module>
    scheduler = APScheduler()
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/flask_apscheduler/scheduler.py", line 37, in __init__
    self._scheduler = scheduler or BackgroundScheduler()
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/base.py", line 97, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/base.py", line 141, in configure
    self._configure(config)
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/base.py", line 711, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                                                                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/usr/local/lib/python3.12/dist-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != -18000. Please, check your config files.
```

**As root (sudo su) user:**

```
/var/www/haproxy-wi/app# python3 tools/sockets.py
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/tools/sockets.py", line 16, in <module>
    import app.modules.db.sql as sql
  File "/var/www/haproxy-wi/app/__init__.py", line 16, in <module>
    scheduler = APScheduler()
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/flask_apscheduler/scheduler.py", line 37, in __init__
    self._scheduler = scheduler or BackgroundScheduler()
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/base.py", line 97, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/base.py", line 141, in configure
    self._configure(config)
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.12/dist-packages/apscheduler/schedulers/base.py", line 711, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                                                                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/usr/local/lib/python3.12/dist-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != -18000. Please, check your config files.

```

**Comment by Aidaho12** [comment]
Quite strange, it does depends on socket tool....

Run it like: tools/socket.py
