### ISSUE TITLE
How to Run From Source?

### ISSUE THREAD

**Issue by mohammed90** [roxy-wi/roxy-wi#407]
I'm trying to add [Caddy](https://caddyserver.com/) support, but I don't see any instructions on how to run roxy-wi from source.

**Comment by Aidaho12** [comment]
Well, you should clone the repo install requirements and dependent: 
```
python3 python3-pip python3-devel python3-cryptography dos2unix httpd mod_ssl python3-mod_wsgi bind-utils nmap
```
put [configs](https://github.com/roxy-wi/roxy-wi/tree/master/config_other) into correct paths, add in sudo apache user without user
geterate ssl and [rsa key](https://roxy-wi.org/update-guide#8)
create folders: /var/{lib,log}/roxy-wi, /etc/roxy-wi

generally that's all. if something does not work look at the http error log and fix it

**Comment by mohammed90** [comment]
My knowledge of running Python apps, especially Flask, is minimal. I have followed the instructions, and I also run `pip install -r requirements.txt` to ensure all requirements are installed. However, I still get 500 error, and these are the printed logs:

```
[Tue Dec 24 08:46:12.072234 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178] mod_wsgi (pid=51390): Failed to exec Python script file '/var/www/haproxy-wi/app/app.wsgi'.
[Tue Dec 24 08:46:12.072278 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178] mod_wsgi (pid=51390): Exception occurred processing WSGI script '/var/www/haproxy-wi/app/app.wsgi'.
[Tue Dec 24 08:46:12.075619 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178] Traceback (most recent call last):
[Tue Dec 24 08:46:12.075643 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178]   File "/var/www/haproxy-wi/app/app.wsgi", line 4, in <module>
[Tue Dec 24 08:46:12.075646 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178]     from app import app as application
[Tue Dec 24 08:46:12.075651 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178]   File "/var/www/haproxy-wi/app/__init__.py", line 1, in <module>
[Tue Dec 24 08:46:12.075653 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178]     from flask import Flask
[Tue Dec 24 08:46:12.075663 2024] [wsgi:error] [pid 51390:tid 135897578284800] [remote ::1:54178] ModuleNotFoundError: No module named 'flask'
```

I've also run `pip install flask` and says the requirement is already satisfied.

**Comment by Aidaho12** [comment]
Hi,

you can install Roxy-WI from package add git origin from github pull it and implement your code for testing purpose
